In [ ]:
#installing SQL Db and pandas packages
!pip -q install duckdb pandas

In [ ]:
#importing the libraries from the packages
import pandas as pd
import duckdb

In [ ]:
#load the dataset file
from google.colab import files
uploaded = files.upload()

Saving DataCoSupplyChainDataset.csv to DataCoSupplyChainDataset.csv

In [ ]:
#check the dataset file is loaded
import os
print(os.getcwd())
print(os.listdir())

/content
['.config', '.ipynb_checkpoints', 'DataCoSupplyChainDataset.csv', 'sample_data']

In [ ]:
df = pd.read_csv("DataCoSupplyChainDataset.csv", encoding="latin1")
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [ ]:
#find the shape of the dataset to confirm the number of rows and columns
df.shape

(180519, 53)

In [ ]:
#list the columns of the dataset
df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [ ]:
#list column names, numbers with data tyeps
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [ ]:
#Standardizing the column names for python and SQL
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df.columns = df.columns.str.replace("-","_")
df.columns.tolist()

['type',
 'days_for_shipping_(real)',
 'days_for_shipment_(scheduled)',
 'benefit_per_order',
 'sales_per_customer',
 'delivery_status',
 'late_delivery_risk',
 'category_id',
 'category_name',
 'customer_city',
 'customer_country',
 'customer_email',
 'customer_fname',
 'customer_id',
 'customer_lname',
 'customer_password',
 'customer_segment',
 'customer_state',
 'customer_street',
 'customer_zipcode',
 'department_id',
 'department_name',
 'latitude',
 'longitude',
 'market',
 'order_city',
 'order_country',
 'order_customer_id',
 'order_date_(dateorders)',
 'order_id',
 'order_item_cardprod_id',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'order_region',
 'order_state',
 'order_status',
 'order_zipcode',
 'product_card_id',
 'product_category_id',
 'product_description',
 'product_image',
 'product_name',
 'product_price',
 'product_status',
 'shipping_date_(dateorders)',
 'shipping_mode']

In [ ]:
#Check for duplicates
df.duplicated().sum()

np.int64(0)

In [ ]:
#convert dates columns to datetime type; errors = 'coerce' will convert bad vaules to null instead of crashing
df['order_date_(dateorders)'] = pd.to_datetime(
    df['order_date_(dateorders)'], errors='coerce'
)

df['shipping_date_(dateorders)'] = pd.to_datetime(
    df['shipping_date_(dateorders)'], errors='coerce'
)

In [ ]:
#Numeric and Business data sanity checking
df[['sales','order_item_quantity','product_price','benefit_per_order']].describe()

               sales  order_item_quantity  product_price  benefit_per_order
count  180519.000000        180519.000000  180519.000000      180519.000000
mean      203.772096             2.127638     141.232550          21.974989
std       132.273077             1.453451     139.732492         104.433526
min         9.990000             1.000000       9.990000       -4274.979980
25%       119.980003             1.000000      50.000000           7.000000
50%       199.919998             1.000000      59.990002          31.520000
75%       299.950012             3.000000     199.990005          64.800003
max      1999.989990             5.000000    1999.989990         911.799988

In [ ]:
#Remove Negative Sales data
df = df[df['sales'] >= 0]

In [ ]:
#Remove Zero Sales quantities
df = df[df['order_item_quantity'] > 0]

In [ ]:
#Check for Null values in key columns
important_cols = [
    'order_id',
    'customer_id',
    'category_name',
    'sales',
    'order_status',
    'shipping_mode'
]
df[important_cols].isnull().sum()

order_id         0
customer_id      0
category_name    0
sales            0
order_status     0
shipping_mode    0
dtype: int64

In [ ]:
#register the dataframe into Duckdb
import duckdb
con =  duckdb.connect()
con.register("orders", df)

In [ ]:
#EDA SQL Queries
#ORDERS
#Revenue and Order Status
#order_details =
con.sql("""
SELECT
  order_status,
  COUNT(DISTINCT order_id) AS total_orders,
  ROUND(SUM(sales),2) AS total_revenue,
  ROUND(AVG(sales),2) AS avg_order_value
FROM orders
GROUP BY order_status
ORDER BY total_revenue DESC
""").df()

#EXPORT SQL OUTPUT TABLE
#CONVERT SQL RESULTS INTO DATAFRAME, AND THEN CONVERT THE DATAFRAME INTO CSV FILE

#order_details.to_csv('order_details.csv', index=False)

#from google.colab import files
#files.download('order_details.csv')

      order_status  total_orders  total_revenue  avg_order_value
0         COMPLETE         21716    12095314.95           203.31
1  PENDING_PAYMENT         14382     8106697.56           203.52
2       PROCESSING          7901     4504063.75           205.65
3          PENDING          7321     4120532.87           203.71
4           CLOSED          7249     4022624.17           205.07
5          ON_HOLD          3624     1981542.71           202.12
6  SUSPECTED_FRAUD          1488      825934.96           203.33
7         CANCELED          1367      744370.40           201.62
8   PAYMENT_REVIEW           704      383653.66           202.67

In [ ]:
#Top Product Categories
#top_product_category =
con.sql("""
SELECT category_name,
  COUNT(DISTINCT order_id) AS orders,
  ROUND(SUM(sales),2) AS revenue
FROM orders
GROUP BY category_name
ORDER BY revenue DESC
LIMIT 10
""").df()

#top_product_category.to_csv('top_product_category.csv', index=False)

#from google.colab import files
#files.download('top_product_category.csv')

          category_name  orders     revenue
0               Fishing   15164  6929653.69
1                Cleats   20386  4431942.78
2      Camping & Hiking   12299  4118425.57
3      Cardio Equipment   11355  3694843.20
4       Women's Apparel   17869  3147800.00
5          Water Sports   13758  3113844.68
6        Men's Footwear   18783  2891757.66
7  Indoor/Outdoor Games   16623  2888993.91
8         Shop By Sport   10136  1309522.04
9             Computers     442   663000.00

In [ ]:
#Average Revenue per Order by Category
avg_rev_per_order_category = con.sql("""
SELECT category_name,
  COUNT(DISTINCT order_id) AS orders,
  ROUND(SUM(sales),2) AS revenue,
  ROUND(SUM(sales)/COUNT(DISTINCT order_id),2) AS avg_order_value
FROM orders
GROUP by category_name
ORDER BY avg_order_value DESC
""").df()

avg_rev_per_order_category.to_csv('avg_rev_per_order_category.csv', index=False)

from google.colab import files
files.download('avg_rev_per_order_category.csv')

In [ ]:
#Profitability by Category
profit_by_category = con.sql("""
SELECT category_name,
  COUNT(DISTINCT order_id) AS orders,
  ROUND(SUM(sales),2) AS revenue,
  ROUND(SUM(benefit_per_order),2) AS profit,
  ROUND(SUM(benefit_per_order)/SUM(sales)*100,2) AS profit_margin_percent
FROM orders
GROUP BY category_name
ORDER BY profit_margin_percent DESC
""").df()

profit_by_category.to_csv('profit_by_category.csv', index=False)

from google.colab import files
files.download('profit_by_category.csv')

In [ ]:
#Categories with High Number of Orders but low margins
high_order_low_margin_products = con.sql("""
SELECT
  category_name,
  COUNT(DISTINCT order_id) AS orders,
  ROUND(SUM(sales),2) AS revenue,
  ROUND(SUM(benefit_per_order),2) AS profit,
  ROUND(SUM(benefit_per_order)/SUM(sales)*100,2) AS profit_margin_percent
FROM orders
GROUP BY category_name
HAVING COUNT(DISTINCT order_id) > 5000
ORDER BY profit_margin_percent ASC
""").df()

high_order_low_margin_products.to_csv('high_order_low_margin_products.csv', index=False)

from google.colab import files
files.download('high_order_low_margin_products.csv')

In [ ]:
#Shipping Mode vs Profitability
shipping_mode_profitability = con.sql("""
SELECT shipping_mode,
  COUNT(DISTINCT order_id) AS orders,
  ROUND(SUM(sales),2) AS revenue,
  ROUND(SUM(benefit_per_order),2) AS profit,
  ROUND(SUM(benefit_per_order)/SUM(sales)*100,2) AS profit_margin_percent
FROM orders
GROUP BY shipping_mode
ORDER BY profit_margin_percent ASC
""").df()

shipping_mode_profitability.to_csv('shipping_mode_profitability.csv', index=False)

from google.colab import files
files.download('shipping_mode_profitability.csv')

In [ ]:
#Late Delivery risk vs Profitability
late_delivery_risk_profitability = con.sql("""
SELECT
    late_delivery_risk,
    COUNT(DISTINCT order_id) AS orders,
    ROUND(SUM(sales),2) AS revenue,
    ROUND(SUM(benefit_per_order),2) AS profit,
    ROUND(SUM(benefit_per_order)/SUM(sales)*100,2) AS profit_margin_percentage
FROM orders
GROUP BY late_delivery_risk
""").df()

late_delivery_risk_profitability.to_csv('late_delivery_risk_profitability.csv', index=False)

from google.colab import files
files.download('late_delivery_risk_profitability.csv')

In [ ]:
#RISKS
#Shipping Mode vs Highest Late Risk
con.sql("""
SELECT
    shipping_mode,
    COUNT(DISTINCT order_id) AS orders,
    COUNT(DISTINCT CASE WHEN late_delivery_risk = 1 THEN order_id END) AS risky_orders,
    ROUND(
        COUNT(DISTINCT CASE WHEN late_delivery_risk = 1 THEN order_id END)
        * 100.0 / COUNT(DISTINCT order_id), 2
    ) AS risk_rate_percentage
FROM orders
GROUP BY shipping_mode
ORDER BY risk_rate_percentage DESC
""").df()

    shipping_mode  orders  risky_orders  risk_rate_percentage
0     First Class   10079          9602                 95.27
1    Second Class   12778          9803                 76.72
2        Same Day    3571          1648                 46.15
3  Standard Class   39324         14995                 38.13

In [ ]:
con.sql("""
SELECT late_delivery_risk, COUNT(*)
FROM orders
GROUP BY late_delivery_risk
""").df()

   late_delivery_risk  count_star()
0                   0         81542
1                   1         98977

In [ ]:
#Regions with Most Risks
con.sql("""
SELECT
    order_region,
    COUNT(DISTINCT order_id) AS orders,
    COUNT(DISTINCT CASE WHEN late_delivery_risk = 1 THEN order_id END) AS risky_orders,
    ROUND(
        COUNT(DISTINCT CASE WHEN late_delivery_risk = 1 THEN order_id END)
        * 100.0 / COUNT(DISTINCT order_id), 2
    ) AS risk_rate_percentage
FROM orders
GROUP BY order_region
ORDER BY risk_rate_percentage DESC
LIMIT 10
""").df()

     order_region  orders  risky_orders  risk_rate_percentage
0  Central Africa     556           320                 57.55
1     East Africa     613           348                 56.77
2  South of  USA     1345           753                 55.99
3       West Asia    2022          1132                 55.98
4  Eastern Europe    1292           723                 55.96
5      South Asia    3335          1865                 55.92
6  Western Europe   10010          5585                 55.79
7  Southeast Asia    4356          2421                 55.58
8    Central Asia     184           102                 55.43
9      US Center     1935          1071                 55.35

In [ ]:
#Risk Impact Score
con.sql("""
SELECT
    order_region,
    COUNT(DISTINCT CASE WHEN late_delivery_risk = 1 THEN order_id END) AS risky_orders,
    ROUND(SUM(CASE WHEN late_delivery_risk = 1 THEN sales ELSE 0 END), 2) AS risky_revenue
FROM orders
GROUP BY order_region
ORDER BY risky_revenue DESC
LIMIT 10
""").df()

      order_region  risky_orders  risky_revenue
0   Western Europe          5585     3292013.64
1  Central America          5156     3110260.23
2    South America          2696     1606545.92
3  Northern Europe          1996     1153862.62
4  Southern Europe          1895     1100896.57
5          Oceania          2382     1079244.38
6   Southeast Asia          2421     1073898.39
7        Caribbean          1487      872376.53
8       South Asia          1865      871471.66
9     West of USA           1451      838331.37

In [ ]:
#Region wise Risk Impact Score
con.sql("""
SELECT
    order_region,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT CASE WHEN late_delivery_risk=1 THEN order_id END) AS risky_orders,
    ROUND(
        COUNT(DISTINCT CASE WHEN late_delivery_risk=1 THEN order_id END)
        *100.0 / COUNT(DISTINCT order_id),2
    ) AS risk_rate_percentage,
    ROUND(SUM(CASE WHEN late_delivery_risk=1 THEN sales ELSE 0 END),2) AS risky_revenue
FROM orders
GROUP BY order_region
ORDER BY risky_revenue DESC
LIMIT 5
""").df()

,order_region,total_orders,risky_orders,risk_rate_percentage,risky_revenue
0,Western Europe,10010,5585,55.79,3292013.64
1,Central America,9396,5156,54.87,3110260.23
2,South America,4979,2696,54.15,1606545.92
3,Northern Europe,3716,1996,53.71,1153862.62
4,Southern Europe,3543,1895,53.49,1100896.57